// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DistSSE.proto

#include "DistSSE.pb.h"
#include "DistSSE.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace DistSSE {

static const char* RPC_method_names[] = {
  "/DistSSE.RPC/setup",
  "/DistSSE.RPC/search",
  "/DistSSE.RPC/update",
  "/DistSSE.RPC/batch_update",
  "/DistSSE.RPC/cache",
  "/DistSSE.RPC/batch_cache",
};

std::unique_ptr< RPC::Stub> RPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RPC::Stub> stub(new RPC::Stub(channel));
  return stub;
}

RPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_setup_(RPC_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_search_(RPC_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_update_(RPC_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_batch_update_(RPC_method_names[3], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_cache_(RPC_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_batch_cache_(RPC_method_names[5], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status RPC::Stub::setup(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_setup_, context, request, response);
}

void RPC::Stub::experimental_async::setup(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_setup_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsyncsetupRaw(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_setup_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsyncsetupRaw(::grpc::ClientContext* context, const ::DistSSE::SetupRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_setup_, context, request, false);
}

::grpc::ClientReader< ::DistSSE::SearchReply>* RPC::Stub::searchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), rpcmethod_search_, context, request);
}

void RPC::Stub::experimental_async::search(::grpc::ClientContext* context, ::DistSSE::SearchRequestMessage* request, ::grpc::experimental::ClientReadReactor< ::DistSSE::SearchReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::DistSSE::SearchReply>::Create(stub_->channel_.get(), stub_->rpcmethod_search_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::DistSSE::SearchReply>* RPC::Stub::AsyncsearchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), cq, rpcmethod_search_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::DistSSE::SearchReply>* RPC::Stub::PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::DistSSE::SearchRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::DistSSE::SearchReply>::Create(channel_.get(), cq, rpcmethod_search_, context, request, false, nullptr);
}

::grpc::Status RPC::Stub::update(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_update_, context, request, response);
}

void RPC::Stub::experimental_async::update(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_update_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsyncupdateRaw(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_update_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsyncupdateRaw(::grpc::ClientContext* context, const ::DistSSE::UpdateRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_update_, context, request, false);
}

::grpc::ClientWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::batch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), rpcmethod_batch_update_, context, response);
}

void RPC::Stub::experimental_async::batch_update(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::experimental::ClientWriteReactor< ::DistSSE::UpdateRequestMessage>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_batch_update_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::Asyncbatch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_update_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::DistSSE::UpdateRequestMessage>* RPC::Stub::PrepareAsyncbatch_updateRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::UpdateRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_update_, context, response, false, nullptr);
}

::grpc::Status RPC::Stub::cache(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_cache_, context, request, response);
}

void RPC::Stub::experimental_async::cache(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage* request, ::DistSSE::ExecuteStatus* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_cache_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::AsynccacheRaw(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_cache_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::DistSSE::ExecuteStatus>* RPC::Stub::PrepareAsynccacheRaw(::grpc::ClientContext* context, const ::DistSSE::CacheRequestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::DistSSE::ExecuteStatus>::Create(channel_.get(), cq, rpcmethod_cache_, context, request, false);
}

::grpc::ClientWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::batch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), rpcmethod_batch_cache_, context, response);
}

void RPC::Stub::experimental_async::batch_cache(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::experimental::ClientWriteReactor< ::DistSSE::CacheRequestMessage>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::DistSSE::CacheRequestMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_batch_cache_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::Asyncbatch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_cache_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::DistSSE::CacheRequestMessage>* RPC::Stub::PrepareAsyncbatch_cacheRaw(::grpc::ClientContext* context, ::DistSSE::ExecuteStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DistSSE::CacheRequestMessage>::Create(channel_.get(), cq, rpcmethod_batch_cache_, context, response, false, nullptr);
}

RPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::SetupRequestMessage, ::DistSSE::ExecuteStatus>(
          std::mem_fn(&RPC::Service::setup), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RPC::Service, ::DistSSE::SearchRequestMessage, ::DistSSE::SearchReply>(
          std::mem_fn(&RPC::Service::search), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus>(
          std::mem_fn(&RPC::Service::update), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[3],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< RPC::Service, ::DistSSE::UpdateRequestMessage, ::DistSSE::ExecuteStatus>(
          std::mem_fn(&RPC::Service::batch_update), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC::Service, ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus>(
          std::mem_fn(&RPC::Service::cache), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_method_names[5],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< RPC::Service, ::DistSSE::CacheRequestMessage, ::DistSSE::ExecuteStatus>(
          std::mem_fn(&RPC::Service::batch_cache), this)));
}

RPC::Service::~Service() {
}

::grpc::Status RPC::Service::setup(::grpc::ServerContext* context, const ::DistSSE::SetupRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::search(::grpc::ServerContext* context, const ::DistSSE::SearchRequestMessage* request, ::grpc::ServerWriter< ::DistSSE::SearchReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::update(::grpc::ServerContext* context, const ::DistSSE::UpdateRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::batch_update(::grpc::ServerContext* context, ::grpc::ServerReader< ::DistSSE::UpdateRequestMessage>* reader, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::cache(::grpc::ServerContext* context, const ::DistSSE::CacheRequestMessage* request, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RPC::Service::batch_cache(::grpc::ServerContext* context, ::grpc::ServerReader< ::DistSSE::CacheRequestMessage>* reader, ::DistSSE::ExecuteStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace DistSSE

