// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DistSSE.proto

#include "DistSSE.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace DistSSE {
class SetupRequestMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetupRequestMessage>
      _instance;
} _SetupRequestMessage_default_instance_;
class SearchRequestMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SearchRequestMessage>
      _instance;
} _SearchRequestMessage_default_instance_;
class SearchReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SearchReply>
      _instance;
} _SearchReply_default_instance_;
class CacheRequestMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CacheRequestMessage>
      _instance;
} _CacheRequestMessage_default_instance_;
class UpdateRequestMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UpdateRequestMessage>
      _instance;
} _UpdateRequestMessage_default_instance_;
class ExecuteStatusDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExecuteStatus>
      _instance;
} _ExecuteStatus_default_instance_;
}  // namespace DistSSE
namespace protobuf_DistSSE_2eproto {
static void InitDefaultsSetupRequestMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_SetupRequestMessage_default_instance_;
    new (ptr) ::DistSSE::SetupRequestMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::SetupRequestMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetupRequestMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetupRequestMessage}, {}};

static void InitDefaultsSearchRequestMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_SearchRequestMessage_default_instance_;
    new (ptr) ::DistSSE::SearchRequestMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::SearchRequestMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SearchRequestMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSearchRequestMessage}, {}};

static void InitDefaultsSearchReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_SearchReply_default_instance_;
    new (ptr) ::DistSSE::SearchReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::SearchReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SearchReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSearchReply}, {}};

static void InitDefaultsCacheRequestMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_CacheRequestMessage_default_instance_;
    new (ptr) ::DistSSE::CacheRequestMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::CacheRequestMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CacheRequestMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCacheRequestMessage}, {}};

static void InitDefaultsUpdateRequestMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_UpdateRequestMessage_default_instance_;
    new (ptr) ::DistSSE::UpdateRequestMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::UpdateRequestMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UpdateRequestMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUpdateRequestMessage}, {}};

static void InitDefaultsExecuteStatus() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DistSSE::_ExecuteStatus_default_instance_;
    new (ptr) ::DistSSE::ExecuteStatus();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DistSSE::ExecuteStatus::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ExecuteStatus =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExecuteStatus}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SetupRequestMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SearchRequestMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SearchReply.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CacheRequestMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UpdateRequestMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExecuteStatus.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SetupRequestMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SetupRequestMessage, setup_size_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchRequestMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchRequestMessage, kw_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchRequestMessage, tw_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchRequestMessage, uc_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::SearchReply, ind_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::CacheRequestMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::CacheRequestMessage, tw_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::CacheRequestMessage, inds_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::UpdateRequestMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::UpdateRequestMessage, l_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::UpdateRequestMessage, e_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::UpdateRequestMessage, counter_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::ExecuteStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DistSSE::ExecuteStatus, status_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::DistSSE::SetupRequestMessage)},
  { 6, -1, sizeof(::DistSSE::SearchRequestMessage)},
  { 14, -1, sizeof(::DistSSE::SearchReply)},
  { 20, -1, sizeof(::DistSSE::CacheRequestMessage)},
  { 27, -1, sizeof(::DistSSE::UpdateRequestMessage)},
  { 35, -1, sizeof(::DistSSE::ExecuteStatus)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_SetupRequestMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_SearchRequestMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_SearchReply_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_CacheRequestMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_UpdateRequestMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::DistSSE::_ExecuteStatus_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DistSSE.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rDistSSE.proto\022\007DistSSE\032\033google/protobu"
      "f/empty.proto\")\n\023SetupRequestMessage\022\022\n\n"
      "setup_size\030\001 \001(\004\":\n\024SearchRequestMessage"
      "\022\n\n\002kw\030\001 \001(\014\022\n\n\002tw\030\002 \001(\014\022\n\n\002uc\030\003 \001(\004\"\032\n\013"
      "SearchReply\022\013\n\003ind\030\001 \001(\014\"/\n\023CacheRequest"
      "Message\022\n\n\002tw\030\001 \001(\014\022\014\n\004inds\030\002 \001(\014\"=\n\024Upd"
      "ateRequestMessage\022\t\n\001l\030\001 \001(\014\022\t\n\001e\030\002 \001(\014\022"
      "\017\n\007counter\030\003 \001(\004\"\037\n\rExecuteStatus\022\016\n\006sta"
      "tus\030\001 \001(\0102\241\003\n\003RPC\022\?\n\005setup\022\034.DistSSE.Set"
      "upRequestMessage\032\026.DistSSE.ExecuteStatus"
      "\"\000\022A\n\006search\022\035.DistSSE.SearchRequestMess"
      "age\032\024.DistSSE.SearchReply\"\0000\001\022A\n\006update\022"
      "\035.DistSSE.UpdateRequestMessage\032\026.DistSSE"
      ".ExecuteStatus\"\000\022I\n\014batch_update\022\035.DistS"
      "SE.UpdateRequestMessage\032\026.DistSSE.Execut"
      "eStatus\"\000(\001\022\?\n\005cache\022\034.DistSSE.CacheRequ"
      "estMessage\032\026.DistSSE.ExecuteStatus\"\000\022G\n\013"
      "batch_cache\022\034.DistSSE.CacheRequestMessag"
      "e\032\026.DistSSE.ExecuteStatus\"\000(\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 757);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DistSSE.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DistSSE_2eproto
namespace DistSSE {

// ===================================================================

void SetupRequestMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetupRequestMessage::kSetupSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetupRequestMessage::SetupRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_SetupRequestMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.SetupRequestMessage)
}
SetupRequestMessage::SetupRequestMessage(const SetupRequestMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  setup_size_ = from.setup_size_;
  // @@protoc_insertion_point(copy_constructor:DistSSE.SetupRequestMessage)
}

void SetupRequestMessage::SharedCtor() {
  setup_size_ = GOOGLE_ULONGLONG(0);
}

SetupRequestMessage::~SetupRequestMessage() {
  // @@protoc_insertion_point(destructor:DistSSE.SetupRequestMessage)
  SharedDtor();
}

void SetupRequestMessage::SharedDtor() {
}

void SetupRequestMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetupRequestMessage::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetupRequestMessage& SetupRequestMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_SetupRequestMessage.base);
  return *internal_default_instance();
}


void SetupRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.SetupRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  setup_size_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool SetupRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.SetupRequestMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 setup_size = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &setup_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.SetupRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.SetupRequestMessage)
  return false;
#undef DO_
}

void SetupRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.SetupRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 setup_size = 1;
  if (this->setup_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->setup_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.SetupRequestMessage)
}

::google::protobuf::uint8* SetupRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.SetupRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 setup_size = 1;
  if (this->setup_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->setup_size(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.SetupRequestMessage)
  return target;
}

size_t SetupRequestMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.SetupRequestMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 setup_size = 1;
  if (this->setup_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->setup_size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetupRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.SetupRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const SetupRequestMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetupRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.SetupRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.SetupRequestMessage)
    MergeFrom(*source);
  }
}

void SetupRequestMessage::MergeFrom(const SetupRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.SetupRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.setup_size() != 0) {
    set_setup_size(from.setup_size());
  }
}

void SetupRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.SetupRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetupRequestMessage::CopyFrom(const SetupRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.SetupRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetupRequestMessage::IsInitialized() const {
  return true;
}

void SetupRequestMessage::Swap(SetupRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetupRequestMessage::InternalSwap(SetupRequestMessage* other) {
  using std::swap;
  swap(setup_size_, other->setup_size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetupRequestMessage::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SearchRequestMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SearchRequestMessage::kKwFieldNumber;
const int SearchRequestMessage::kTwFieldNumber;
const int SearchRequestMessage::kUcFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SearchRequestMessage::SearchRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_SearchRequestMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.SearchRequestMessage)
}
SearchRequestMessage::SearchRequestMessage(const SearchRequestMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  kw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.kw().size() > 0) {
    kw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.kw_);
  }
  tw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tw().size() > 0) {
    tw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tw_);
  }
  uc_ = from.uc_;
  // @@protoc_insertion_point(copy_constructor:DistSSE.SearchRequestMessage)
}

void SearchRequestMessage::SharedCtor() {
  kw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uc_ = GOOGLE_ULONGLONG(0);
}

SearchRequestMessage::~SearchRequestMessage() {
  // @@protoc_insertion_point(destructor:DistSSE.SearchRequestMessage)
  SharedDtor();
}

void SearchRequestMessage::SharedDtor() {
  kw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SearchRequestMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SearchRequestMessage::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SearchRequestMessage& SearchRequestMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_SearchRequestMessage.base);
  return *internal_default_instance();
}


void SearchRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.SearchRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uc_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool SearchRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.SearchRequestMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes kw = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_kw()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes tw = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_tw()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uc = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uc_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.SearchRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.SearchRequestMessage)
  return false;
#undef DO_
}

void SearchRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.SearchRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes kw = 1;
  if (this->kw().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->kw(), output);
  }

  // bytes tw = 2;
  if (this->tw().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->tw(), output);
  }

  // uint64 uc = 3;
  if (this->uc() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->uc(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.SearchRequestMessage)
}

::google::protobuf::uint8* SearchRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.SearchRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes kw = 1;
  if (this->kw().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->kw(), target);
  }

  // bytes tw = 2;
  if (this->tw().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->tw(), target);
  }

  // uint64 uc = 3;
  if (this->uc() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->uc(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.SearchRequestMessage)
  return target;
}

size_t SearchRequestMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.SearchRequestMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes kw = 1;
  if (this->kw().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->kw());
  }

  // bytes tw = 2;
  if (this->tw().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->tw());
  }

  // uint64 uc = 3;
  if (this->uc() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->uc());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SearchRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.SearchRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const SearchRequestMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SearchRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.SearchRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.SearchRequestMessage)
    MergeFrom(*source);
  }
}

void SearchRequestMessage::MergeFrom(const SearchRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.SearchRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.kw().size() > 0) {

    kw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.kw_);
  }
  if (from.tw().size() > 0) {

    tw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tw_);
  }
  if (from.uc() != 0) {
    set_uc(from.uc());
  }
}

void SearchRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.SearchRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SearchRequestMessage::CopyFrom(const SearchRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.SearchRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchRequestMessage::IsInitialized() const {
  return true;
}

void SearchRequestMessage::Swap(SearchRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SearchRequestMessage::InternalSwap(SearchRequestMessage* other) {
  using std::swap;
  kw_.Swap(&other->kw_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  tw_.Swap(&other->tw_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(uc_, other->uc_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SearchRequestMessage::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SearchReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SearchReply::kIndFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SearchReply::SearchReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_SearchReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.SearchReply)
}
SearchReply::SearchReply(const SearchReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ind_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ind().size() > 0) {
    ind_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ind_);
  }
  // @@protoc_insertion_point(copy_constructor:DistSSE.SearchReply)
}

void SearchReply::SharedCtor() {
  ind_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SearchReply::~SearchReply() {
  // @@protoc_insertion_point(destructor:DistSSE.SearchReply)
  SharedDtor();
}

void SearchReply::SharedDtor() {
  ind_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SearchReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SearchReply::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SearchReply& SearchReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_SearchReply.base);
  return *internal_default_instance();
}


void SearchReply::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.SearchReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ind_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SearchReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.SearchReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes ind = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ind()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.SearchReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.SearchReply)
  return false;
#undef DO_
}

void SearchReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.SearchReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ind = 1;
  if (this->ind().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->ind(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.SearchReply)
}

::google::protobuf::uint8* SearchReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.SearchReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ind = 1;
  if (this->ind().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->ind(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.SearchReply)
  return target;
}

size_t SearchReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.SearchReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes ind = 1;
  if (this->ind().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->ind());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SearchReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.SearchReply)
  GOOGLE_DCHECK_NE(&from, this);
  const SearchReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SearchReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.SearchReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.SearchReply)
    MergeFrom(*source);
  }
}

void SearchReply::MergeFrom(const SearchReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.SearchReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ind().size() > 0) {

    ind_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ind_);
  }
}

void SearchReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.SearchReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SearchReply::CopyFrom(const SearchReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.SearchReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchReply::IsInitialized() const {
  return true;
}

void SearchReply::Swap(SearchReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SearchReply::InternalSwap(SearchReply* other) {
  using std::swap;
  ind_.Swap(&other->ind_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SearchReply::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CacheRequestMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CacheRequestMessage::kTwFieldNumber;
const int CacheRequestMessage::kIndsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CacheRequestMessage::CacheRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_CacheRequestMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.CacheRequestMessage)
}
CacheRequestMessage::CacheRequestMessage(const CacheRequestMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  tw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tw().size() > 0) {
    tw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tw_);
  }
  inds_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.inds().size() > 0) {
    inds_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inds_);
  }
  // @@protoc_insertion_point(copy_constructor:DistSSE.CacheRequestMessage)
}

void CacheRequestMessage::SharedCtor() {
  tw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  inds_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CacheRequestMessage::~CacheRequestMessage() {
  // @@protoc_insertion_point(destructor:DistSSE.CacheRequestMessage)
  SharedDtor();
}

void CacheRequestMessage::SharedDtor() {
  tw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  inds_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CacheRequestMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CacheRequestMessage::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CacheRequestMessage& CacheRequestMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_CacheRequestMessage.base);
  return *internal_default_instance();
}


void CacheRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.CacheRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  inds_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool CacheRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.CacheRequestMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes tw = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_tw()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes inds = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_inds()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.CacheRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.CacheRequestMessage)
  return false;
#undef DO_
}

void CacheRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.CacheRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes tw = 1;
  if (this->tw().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->tw(), output);
  }

  // bytes inds = 2;
  if (this->inds().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->inds(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.CacheRequestMessage)
}

::google::protobuf::uint8* CacheRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.CacheRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes tw = 1;
  if (this->tw().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->tw(), target);
  }

  // bytes inds = 2;
  if (this->inds().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->inds(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.CacheRequestMessage)
  return target;
}

size_t CacheRequestMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.CacheRequestMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes tw = 1;
  if (this->tw().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->tw());
  }

  // bytes inds = 2;
  if (this->inds().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->inds());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CacheRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.CacheRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CacheRequestMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CacheRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.CacheRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.CacheRequestMessage)
    MergeFrom(*source);
  }
}

void CacheRequestMessage::MergeFrom(const CacheRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.CacheRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tw().size() > 0) {

    tw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tw_);
  }
  if (from.inds().size() > 0) {

    inds_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inds_);
  }
}

void CacheRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.CacheRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CacheRequestMessage::CopyFrom(const CacheRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.CacheRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CacheRequestMessage::IsInitialized() const {
  return true;
}

void CacheRequestMessage::Swap(CacheRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CacheRequestMessage::InternalSwap(CacheRequestMessage* other) {
  using std::swap;
  tw_.Swap(&other->tw_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  inds_.Swap(&other->inds_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CacheRequestMessage::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UpdateRequestMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateRequestMessage::kLFieldNumber;
const int UpdateRequestMessage::kEFieldNumber;
const int UpdateRequestMessage::kCounterFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateRequestMessage::UpdateRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_UpdateRequestMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.UpdateRequestMessage)
}
UpdateRequestMessage::UpdateRequestMessage(const UpdateRequestMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  l_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.l().size() > 0) {
    l_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.l_);
  }
  e_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.e().size() > 0) {
    e_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.e_);
  }
  counter_ = from.counter_;
  // @@protoc_insertion_point(copy_constructor:DistSSE.UpdateRequestMessage)
}

void UpdateRequestMessage::SharedCtor() {
  l_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  e_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  counter_ = GOOGLE_ULONGLONG(0);
}

UpdateRequestMessage::~UpdateRequestMessage() {
  // @@protoc_insertion_point(destructor:DistSSE.UpdateRequestMessage)
  SharedDtor();
}

void UpdateRequestMessage::SharedDtor() {
  l_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  e_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UpdateRequestMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UpdateRequestMessage::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UpdateRequestMessage& UpdateRequestMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_UpdateRequestMessage.base);
  return *internal_default_instance();
}


void UpdateRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.UpdateRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  l_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  e_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  counter_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool UpdateRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.UpdateRequestMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes l = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_l()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes e = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_e()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 counter = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &counter_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.UpdateRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.UpdateRequestMessage)
  return false;
#undef DO_
}

void UpdateRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.UpdateRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes l = 1;
  if (this->l().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->l(), output);
  }

  // bytes e = 2;
  if (this->e().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->e(), output);
  }

  // uint64 counter = 3;
  if (this->counter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->counter(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.UpdateRequestMessage)
}

::google::protobuf::uint8* UpdateRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.UpdateRequestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes l = 1;
  if (this->l().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->l(), target);
  }

  // bytes e = 2;
  if (this->e().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->e(), target);
  }

  // uint64 counter = 3;
  if (this->counter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->counter(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.UpdateRequestMessage)
  return target;
}

size_t UpdateRequestMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.UpdateRequestMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes l = 1;
  if (this->l().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->l());
  }

  // bytes e = 2;
  if (this->e().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->e());
  }

  // uint64 counter = 3;
  if (this->counter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->counter());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.UpdateRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateRequestMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.UpdateRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.UpdateRequestMessage)
    MergeFrom(*source);
  }
}

void UpdateRequestMessage::MergeFrom(const UpdateRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.UpdateRequestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.l().size() > 0) {

    l_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.l_);
  }
  if (from.e().size() > 0) {

    e_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.e_);
  }
  if (from.counter() != 0) {
    set_counter(from.counter());
  }
}

void UpdateRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.UpdateRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateRequestMessage::CopyFrom(const UpdateRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.UpdateRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateRequestMessage::IsInitialized() const {
  return true;
}

void UpdateRequestMessage::Swap(UpdateRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateRequestMessage::InternalSwap(UpdateRequestMessage* other) {
  using std::swap;
  l_.Swap(&other->l_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  e_.Swap(&other->e_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(counter_, other->counter_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UpdateRequestMessage::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ExecuteStatus::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExecuteStatus::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExecuteStatus::ExecuteStatus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DistSSE_2eproto::scc_info_ExecuteStatus.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DistSSE.ExecuteStatus)
}
ExecuteStatus::ExecuteStatus(const ExecuteStatus& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:DistSSE.ExecuteStatus)
}

void ExecuteStatus::SharedCtor() {
  status_ = false;
}

ExecuteStatus::~ExecuteStatus() {
  // @@protoc_insertion_point(destructor:DistSSE.ExecuteStatus)
  SharedDtor();
}

void ExecuteStatus::SharedDtor() {
}

void ExecuteStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ExecuteStatus::descriptor() {
  ::protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ExecuteStatus& ExecuteStatus::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DistSSE_2eproto::scc_info_ExecuteStatus.base);
  return *internal_default_instance();
}


void ExecuteStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:DistSSE.ExecuteStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_ = false;
  _internal_metadata_.Clear();
}

bool ExecuteStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DistSSE.ExecuteStatus)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DistSSE.ExecuteStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DistSSE.ExecuteStatus)
  return false;
#undef DO_
}

void ExecuteStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DistSSE.ExecuteStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DistSSE.ExecuteStatus)
}

::google::protobuf::uint8* ExecuteStatus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DistSSE.ExecuteStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DistSSE.ExecuteStatus)
  return target;
}

size_t ExecuteStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DistSSE.ExecuteStatus)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExecuteStatus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DistSSE.ExecuteStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const ExecuteStatus* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExecuteStatus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DistSSE.ExecuteStatus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DistSSE.ExecuteStatus)
    MergeFrom(*source);
  }
}

void ExecuteStatus::MergeFrom(const ExecuteStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DistSSE.ExecuteStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    set_status(from.status());
  }
}

void ExecuteStatus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DistSSE.ExecuteStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExecuteStatus::CopyFrom(const ExecuteStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DistSSE.ExecuteStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExecuteStatus::IsInitialized() const {
  return true;
}

void ExecuteStatus::Swap(ExecuteStatus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExecuteStatus::InternalSwap(ExecuteStatus* other) {
  using std::swap;
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExecuteStatus::GetMetadata() const {
  protobuf_DistSSE_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DistSSE_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace DistSSE
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::SetupRequestMessage* Arena::CreateMaybeMessage< ::DistSSE::SetupRequestMessage >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::SetupRequestMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::SearchRequestMessage* Arena::CreateMaybeMessage< ::DistSSE::SearchRequestMessage >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::SearchRequestMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::SearchReply* Arena::CreateMaybeMessage< ::DistSSE::SearchReply >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::SearchReply >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::CacheRequestMessage* Arena::CreateMaybeMessage< ::DistSSE::CacheRequestMessage >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::CacheRequestMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::UpdateRequestMessage* Arena::CreateMaybeMessage< ::DistSSE::UpdateRequestMessage >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::UpdateRequestMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DistSSE::ExecuteStatus* Arena::CreateMaybeMessage< ::DistSSE::ExecuteStatus >(Arena* arena) {
  return Arena::CreateInternal< ::DistSSE::ExecuteStatus >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
